config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  get 'reviews/pending', action: :show_pending, controller: 'reviews', as: 'pending_reviews'
  resources :reviews, except: :edit

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/review.rb
require 'git'
require 'securerandom'

class Review < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  before_create :generate_repo_slug, :initialize_github_repo
  before_destroy :delete_github_repo
  
  private
  def initialize_github_repo
    Git.create_repo(git_repo, user.github_username)
  end

  def delete_github_repo
    Git.delete_repo(git_repo)
  end

  def generate_repo_slug
    self.git_repo = user.github_username + SecureRandom.hex(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.github_username = auth.info.nickname
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_ownership, only: [:destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.where(user: current_user)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @git_clone_command = "$ git clone " + Git.get_git_url(@review.git_repo)
    @git_add_remote_command = "$ git add remote levelup " + Git.get_git_url(@review.git_repo) +
      "\n$ git push levelup master"
    @invite_url = Git.get_invite_url(@review.git_repo)
  end

  def show_pending
    @reviews = Review.select { |r| r.reviewers.length == 0 }
    render :index
  end

  # GET /reviews/new
  def new
    @review = Review.new
    create
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new
    @review.owner = current_user
    current_user.reviews << @review

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  def check_ownership
    unless @review.user == current_user
      respond_to do |format|
        format.html { redirect_to reviews_url, notice: "You aren't allowed to do that.", status: :unauthorized}
        format.json { head :no_content, status: :unauthorized }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Levelup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    
  </head>

  <body>
    <div class="container pt-5">
      <% if notice %>
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <p><%= notice %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <% if alert %>
        </div>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <p><%= alert %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_dashboard.html.erb
<ul>
  <li><%= link_to "Get my code reviewed", new_review_path %></li>
  <li><%= link_to "My in-progress reviews", reviews_path %></li>
  <li><%= link_to "Review other folks' code", pending_reviews_path %></li>
</ul>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-lg-6 col-sm-12">
    <h1>levelup</h1>

    <p><em>Level up your programming skills – get code reviews from others</em></p>

    <% if user_signed_in? %>
      <%= render "pages/dashboard" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

    <% else %>
      <%= link_to "Sign in with GitHub", user_github_omniauth_authorize_path %>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<h1>My reviews</h1>

<table>
  <thead>
    <tr>
      <th>Repo name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.git_repo %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<h1>Let's review your code! 🙌</h1>

<p>A new repo has been created for you!<p>

<h2>1. Accept invitation</h2>
<p>First, <%= link_to "accept the collaboration invite on GitHub", @invite_url %>.</p>

<h2>2. Clone repo and commit</h2>
<p>Clone the repo locally:</p>
<pre><%= @git_clone_command %></pre>

<p>Then, add your code. When you're done, commit it and push.</p>

<h3>I already have a repo</h3>
<p>No problem – just run these commands to add a new remote and push your code up:</p>

<pre><%= @git_add_remote_command %></pre>

<h2>3. Submit for review</h2>
<p><em>Waiting for commit...</em></p>

<%= link_to 'Back', reviews_path %>